version: "3"
services:
  # Server instances
  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - 8080:8080
    container_name: api
  api-backup:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - 8081:8080
    container_name: api-backup

  # Observability
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - api
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - prometheus

  # Load balancer
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - api-backup
