services:
  # Server instances
  api-primary:
    container_name: api-primary
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  api-secondary:
    container_name: api-secondary
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080

  # Load balancer
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-primary
      - api-secondary
